from ._connection import DatabaseError, DB_FILENAME, get_connection, get_db_path
from ._schema import init_db
from ._config import get_app_config, set_app_config
from ._printer import (
    delete_printer_record,
    get_all_printers,
    get_all_printers_full,
    get_existing_device_ids,
    get_printer_by_id,
    get_printer_id_by_device_id,
    get_printer_stats_all,
    insert_printer,
    update_printer,
    update_printer_image_url,
    upsert_printer,
)
from ._task import (
    delete_manual_task,
    delete_unmapped_null_slot_ptf,
    get_recent_tasks,
    get_task_with_filaments,
    get_tasks_page,
    insert_manual_task,
    insert_print_task_filament,
    replace_task_filaments,
    sync_task_filaments,
    update_manual_task,
    update_task_cover_if_null,
    update_task_cover_url,
    upsert_print_task,
)
from ._filament import (
    delete_spool,
    get_all_mappings_for_export,
    get_all_spools,
    get_ignored_filaments,
    get_mapped_filament_by_id,
    get_mapped_filaments,
    get_ptf_by_id,
    get_ptf_material,
    get_ptf_row_by_task_and_slot,
    get_ptf_row_for_mapping,
    get_ptf_row_with_spool,
    get_spool_by_id,
    get_spool_id_by_uid,
    get_spool_last_used_map,
    get_spool_used_weight,
    get_task_id_by_external_id,
    get_tasks_for_spool,
    get_tasks_grouped_by_spool,
    get_unmapped_filaments,
    ignore_filament,
    insert_spool,
    map_filament_to_spool,
    set_ptf_ignored,
    unignore_filament,
    unmap_filament,
    update_ptf_material,
    update_spool,
)
from ._analytics import (
    get_adjacent_task_dates,
    get_color_usage_stats,
    get_cost_breakdown,
    get_cross_day_ranges_for_year,
    get_cross_day_tasks_for_date,
    get_daily_filament_summary,
    get_duration_histogram,
    get_heatmap_available_years,
    get_heatmap_data,
    get_heatmap_data_for_year,
    get_material_usage_stats,
    get_month_to_date_filament_rows,
    get_month_to_date_stats,
    get_monthly_trend,
    get_printer_usage_stats,
    get_spool_color_usage_stats,
    get_spool_cost_ranking,
    get_tasks_for_date,
    get_weekday_stats,
)

__all__ = [
    # connection & base
    "DatabaseError",
    "DB_FILENAME",
    "get_connection",
    "get_db_path",
    # schema
    "init_db",
    # app config
    "get_app_config",
    "set_app_config",
    # printer
    "delete_printer_record",
    "get_all_printers",
    "get_all_printers_full",
    "get_existing_device_ids",
    "get_printer_by_id",
    "get_printer_id_by_device_id",
    "get_printer_stats_all",
    "insert_printer",
    "update_printer",
    "update_printer_image_url",
    "upsert_printer",
    # task
    "delete_manual_task",
    "delete_unmapped_null_slot_ptf",
    "get_recent_tasks",
    "get_task_with_filaments",
    "get_tasks_page",
    "insert_manual_task",
    "insert_print_task_filament",
    "replace_task_filaments",
    "sync_task_filaments",
    "update_manual_task",
    "update_task_cover_if_null",
    "update_task_cover_url",
    "upsert_print_task",
    # filament
    "delete_spool",
    "get_all_mappings_for_export",
    "get_all_spools",
    "get_ignored_filaments",
    "get_mapped_filament_by_id",
    "get_mapped_filaments",
    "get_ptf_by_id",
    "get_ptf_material",
    "get_ptf_row_by_task_and_slot",
    "get_ptf_row_for_mapping",
    "get_ptf_row_with_spool",
    "get_spool_by_id",
    "get_spool_id_by_uid",
    "get_spool_last_used_map",
    "get_spool_used_weight",
    "get_task_id_by_external_id",
    "get_tasks_for_spool",
    "get_tasks_grouped_by_spool",
    "get_unmapped_filaments",
    "ignore_filament",
    "insert_spool",
    "map_filament_to_spool",
    "set_ptf_ignored",
    "unignore_filament",
    "unmap_filament",
    "update_ptf_material",
    "update_spool",
    # analytics
    "get_adjacent_task_dates",
    "get_color_usage_stats",
    "get_cost_breakdown",
    "get_cross_day_ranges_for_year",
    "get_cross_day_tasks_for_date",
    "get_daily_filament_summary",
    "get_duration_histogram",
    "get_heatmap_available_years",
    "get_heatmap_data",
    "get_heatmap_data_for_year",
    "get_material_usage_stats",
    "get_month_to_date_filament_rows",
    "get_month_to_date_stats",
    "get_monthly_trend",
    "get_printer_usage_stats",
    "get_spool_color_usage_stats",
    "get_spool_cost_ranking",
    "get_tasks_for_date",
    "get_weekday_stats",
]
